# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='userName',
            new_name='user_name',
        ),
    ]
