# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0005_auto_20181119_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followingsmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
