# Generated by Django 2.0 on 2018-11-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0006_auto_20181123_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='directions',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='ingredients',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
