# Generated by Django 2.0 on 2018-11-30 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0007_auto_20181130_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
