# Generated by Django 2.0 on 2018-12-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='directions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
    ]
