# Generated by Django 2.0 on 2018-12-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181207_1046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowingsModel',
            new_name='Followings',
        ),
        migrations.RenameModel(
            old_name='RecipeModel',
            new_name='Recipe',
        ),
    ]
